networks:
  llama-net:

services:
  llm-model-manager:
    volumes:
      - ./src/backend:/app/backend
      - ./src/frontend/js:/app/frontend/js
      - ./src/frontend/index.html:/app/frontend/index.html
    command: ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
